#可以去源码的org.springframework.cloud.netflix.eureka.server.EurekaServerConfigBean这个类里面查看都有哪些配置项、该怎么写server配置（不同版本可能会有不同）
#可以去源码的EurekaInstanceConfigBean Eureka Client实例配置
#可以去源码的EurekaClientConfigBean 客户端和服务器的交互配置

server:
  port: 9002

#应用名称及验证账号
spring:
  application:
    name: sms-service
  cloud:
    service-registry:
      auto-registration:
        enabled: true

eureka:
  client:
    #设置服务注册中心的URL, 集群的话，向一个IP注册就行, 会被封装成EurekaClientConfig，与Eureka服务器交互的
    service-url:
      defaultZone: http://root:root@eureka-7901:7901/eureka/
    #在client端配置，将自己的将康状态传播到Server 健康检查组件（web）会显示哪里有问题了，也就是说心跳能告诉server
    #还活着，这里的healthcheck能告诉server生活质量。后面讲健康检查监控的时候会用到这个地方
    #http://localhost:9001/actuator/health http://localhost:9001/actuator/info
    healthcheck:
      enabled: true
    #Client自身的配置信息
  instance:
    hostname: localhost
    # 踩坑！相同IP不同的Port只有一个实例注册进了Eureka
      #
      #原因是所有的机器都是instance-id: sms-service 这个ID都一样不行，否则Eureka只认一个，只有当这个下线之后，另一个不认的才能顶上来。
      #启发：反着用这一招，可以做主备高可用
    #
    #https://www.zhihu.com/question/62914011
    instance-id: sms-service
    #prefer-ip-address: true
    #ip-address: 127.0.0.1
